name: Build and Test
on: [push, pull_request]
jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x
    - name: Restore Dependencies
      run: dotnet restore
    # Debug and Release might be different due to conditional compilation, so validate both.
    - name: Build (Debug)
      run: dotnet build --configuration Debug --no-restore
    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore
    - name: Test (Debug)
      run: dotnet test --configuration Debug --no-build --nologo
    - name: Test (Release)
      run: dotnet test --configuration Release --no-build --nologo
